version: '3.8'
#use dockerfile in /app directory to build application and listen on 5000 port
services:
  flask-app:
    build:
      context: ./app
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql2
      DB_PORT: 3306
      DB_NAME: flaskdb
      DB_USER: flaskuser
      DB_PASSWORD: flaskpassword
    depends_on:
      - mysql

# use official mysql image from docker hub to buil mysql database server on container
  mysql:
    image: mysql:8.0
    container_name: mysql2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: loginapp
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
